### ISSUE TITLE
No implementation for play.modules.reactivemongo.ReactiveMongoApi was bound.

### ISSUE THREAD

**Issue by coder-han** [sgodbillon/reactivemongo-demo-app#13]
No implementation for play.modules.reactivemongo.ReactiveMongoApi was bound.

**Comment by coder-han** [comment]
application.conf  add play.modules.enabled += "play.modules.reactivemongo.ReactiveMongoModule"

**Comment by sravanikopparapu** [comment]
thank you very much ,it is really working  :-)

**Comment by kyrsideris** [comment]
Thanks! I had the same error because the alternative configuration file was not including the original config file properly and the `play.modules.enabled` was not discoverable although present:
https://www.playframework.com/documentation/2.5.x/ProductionConfiguration#Using--Dconfig.file
